datasets:
  name: wikimedia/wikipedia
  id_config: 20231101.en
  en_config: 20231101.id
  max_row_datasets: 25000
  output_dataset_raw: data/pretrain/raw/wiki_en_id.txt

tokenizer:
  vocab_size: 8000
  seed_vocab_size: 30000
  max_piece_length: 12
  num_em_steps: 4
  shrinking_factor: 0.75
  smoothing: 1e-8
  whitespace_marker: _
  num_extra_ids: 100
  output_tokenizer_path: model/tokenizer/tokenizer/states.json